# -*- coding: utf-8 -*-
"""Excercise02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zp7r5fR0rRo1Fn2gD96KxzA5KtDukKu
"""

import numpy as np
import math
x = list(np.random.randint(0,2, size=10000) + np.random.randint(0,2, size=10000))
X = set(x)
print(x)
print(X)

P = [x.count(i)/len(x) for i in X]
print(P)

EX = 0
for i in X:
	EX = EX + i * P[i - 1]
print(EX)

VarX = 0
for i in X:
    VarX = VarX + (i - EX) ** 2 * P[i - 1]
print(VarX)

SD = math.sqrt(VarX)
print(SD)

e = sum([x.count(i) /len(x) for i in X if i != 0])
print(e)

