# -*- coding: utf-8 -*-
"""ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_9fjIUfJM6F_KYTjrCj30o-6cdBhHgUn
"""

# Bai1
import numpy as np
import math
X = list(np.random.choice([0, 1, 2, 3, 4, 5], size=3650, p=[0.1, 0.2, 0.3, 0.2, 0.15, 0.05]))
P = [X.count(i) / len(X) for i in set(X)]
print(P)

EX = 0
for x in set(X):
    EX = EX + (x * P[x-1])
print(EX)

VarX = 0
for x in set(X):
    VarX = VarX + (x-EX)**2 * P[x-1]
print(VarX)

SD = math.sqrt(VarX)
print(SD)

a = sum([X.count(i) / len(X) for i in set(X) if i >= 3]) 
print(a)