USE MASTER
GO

DROP DATABASE IF EXISTS STUDENTMANAGE 
GO

CREATE DATABASE STUDENTMANAGE
GO 

USE STUDENTMANAGE
GO

CREATE TABLE DEPARTMENT(
	D_ID VARCHAR(10) NOT NULL,
	D_NAME VARCHAR(30) NOT NULL,
	D_YEAR INT NOT NULL,

	PRIMARY KEY(D_ID)
)

CREATE TABLE STUDENT(
	S_ID VARCHAR(10) NOT NULL,
	S_NAME VARCHAR(30) NOT NULL,
	S_YEAR DATE,
	ID VARCHAR (10) NOT NULL,

	PRIMARY KEY(S_ID)
)

CREATE TABLE COURSES(
	C_ID VARCHAR(10) NOT NULL,
	C_NAME VARCHAR(30) NOT NULL,
	CREDIT INT NOT NULL,
	ID VARCHAR (10) NOT NULL,

	PRIMARY KEY(C_ID)
)

CREATE TABLE CONDITION(
	CID VARCHAR(10) NOT NULL,
	PRE_CID VARCHAR(10) NOT NULL,

	PRIMARY KEY(CID, PRE_CID)
)

CREATE TABLE RESULT(
	R_SID VARCHAR(10) NOT NULL,
	R_CID VARCHAR(10) NOT NULL,
	SCORE FLOAT NOT NULL,

	--PRIMARY KEY(R_SID, R_CID)
)

ALTER TABLE COURSES ADD CONSTRAINT FK_COURSES_ID FOREIGN KEY (ID) REFERENCES DEPARTMENT(D_ID)

ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_ID FOREIGN KEY (ID) REFERENCES DEPARTMENT(D_ID)

ALTER TABLE CONDITION ADD 
	CONSTRAINT FK_CONDITION_CID FOREIGN KEY (CID) REFERENCES COURSES(C_ID),
	CONSTRAINT FK_CONDITION_PRE_CID FOREIGN KEY (PRE_CID) REFERENCES COURSES(C_ID)

INSERT INTO DEPARTMENT
VALUES
		('IT', 'Information Technology', 2012),
		('ET', 'Electronic Technology', 1997),
		('BT', 'Biotechnology', 1997),
		('FL', 'Foreign language', 2000),
		('CT', 'Chemical Technology', 2011);

INSERT INTO STUDENT
VALUES
		('S01','Phuoc Tran','1990/02/24','IT'),
		('S02','Timothy','2000/12/12','IT'),
		('S03','Kaily','2001/10/01','ET'),
		('S04','Tam Nguyen','1998/12/10','ET'),
		('S05','Lee Nguyen','1999/02/28','BT');

	
INSERT INTO COURSES
VALUES
		('OOP','Object Oriented Programming','4','IT'),
		('PM','Programming Method','4','IT'),
		('DBS','Databased System','4','IT'),
		('SE','Software Engineering','4','IT'),
		('CN','Computer Network','3','IT');

INSERT INTO CONDITION
VALUES
		('OOP','PM'),
		('DBS','PM'),
		('DBS','OOP'),
		('SE','OOP'),
		('SE','DBS');

INSERT INTO RESULT
VALUES
		('S01','PM','9.5'),
		('S01','OOP','10'),
		('S02','PM','4.5'),
		('S02','DBS','6.0'),
		('S03','DBS','8.0');


UPDATE STUDENT
SET S_YEAR = '1999/02/20'
WHERE S_ID = 'S01';

SELECT * FROM STUDENT
SELECT * FROM RESULT

UPDATE RESULT
SET SCORE +=1
WHERE R_SID = 'S02' AND R_CID= 'PM';

DELETE FROM RESULT
WHERE SCORE < 5

SELECT * FROM RESULT

ALTER TABLE STUDENT
ADD PHONE INT;

ALTER TABLE STUDENT ALTER COLUMN PHONE VARCHAR(255)

SELECT * FROM STUDENT

ALTER TABLE STUDENT
ADD CONSTRAINT PHONE
DEFAULT 'NONE' FOR PHONE;

SELECT * FROM STUDENT
--d
ALTER TABLE RESULT
ADD CONSTRAINT PK_S_ID_C_ID PRIMARY KEY (R_SID, R_CID);
--e
ALTER TABLE RESULT ADD 
	CONSTRAINT FK_RESULT_R_SID FOREIGN KEY (R_SID) REFERENCES STUDENT(S_ID),
	CONSTRAINT FK_RESULT_R_CID FOREIGN KEY (R_CID) REFERENCES COURSES(C_ID)
--F
DELETE RESULT WHERE SCORE < 0 AND SCORE > 10
ALTER TABLE RESULT
	ADD CONSTRAINT CHECK_SCORE CHECK (SCORE >= 0 AND SCORE <= 10)

SELECT * FROM RESULT

DELETE COURSES WHERE CREDIT < 1 AND CREDIT > 12
ALTER TABLE COURSES
	ADD CONSTRAINT CHECK_CREDIT CHECK (CREDIT >= 1 AND CREDIT <= 12)

ALTER TABLE COURSES ADD UNIQUE (C_NAME)

SELECT * FROM COURSES
--G
ALTER TABLE STUDENT
DROP CONSTRAINT PHONE;

ALTER TABLE STUDENT
DROP COLUMN PHONE;

SELECT * FROM STUDENT
--H
ALTER TABLE COURSES
DROP CONSTRAINT CHECK_CREDIT




