USE MASTER
GO
DROP DATABASE IF EXISTS TRANTHIVEN_52100674_ASSIGNMENT
GO
CREATE DATABASE TRANTHIVEN_52100674_ASSIGNMENT
GO

USE TRANTHIVEN_52100674_ASSIGNMENT
GO

IF OBJECT_ID('DM_NHANVIEN') IS NOT NULL
  DROP TABLE DM_NHANVIEN
IF OBJECT_ID('DM_PHONGBAN') IS NOT NULL
  DROP TABLE DM_PHONGBAN
IF OBJECT_ID('DM_BANGCAP') IS NOT NULL
  DROP TABLE DM_BANGCAP
IF OBJECT_ID('DM_TRINHDO') IS NOT NULL
  DROP TABLE DM_TRINHDO
IF OBJECT_ID('DM_NGANH') IS NOT NULL
  DROP TABLE DM_NGANH
IF OBJECT_ID('DM_THUONG') IS NOT NULL
  DROP TABLE DM_THUONG
IF OBJECT_ID('DM_QHGIADINH') IS NOT NULL
  DROP TABLE DM_QHGIADINH
IF OBJECT_ID('DM_KINANG') IS NOT NULL
  DROP TABLE DM_KINANG
IF OBJECT_ID('DM_KINANG_NV') IS NOT NULL
  DROP TABLE DM_KINANG_NV
IF OBJECT_ID('NV_FULLTIME') IS NOT NULL
  DROP TABLE NV_FULLTIME
IF OBJECT_ID('NV_PARTTIME') IS NOT NULL
  DROP TABLE NV_PARTTIME
IF OBJECT_ID('NV_TUVAN') IS NOT NULL
  DROP TABLE NV_TUVAN
GO

--CREATE TABLE
CREATE TABLE DM_NHANVIEN(
	MANV VARCHAR(255),
	HO VARCHAR (255),
	TENDEM VARCHAR (255),
	TEN VARCHAR (255),
	SODIENTHOAI VARCHAR(20),
	DIACHI VARCHAR(255),
	NGAYSINH DATE,
	MAPB VARCHAR(255),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)
GO

CREATE TABLE DM_PHONGBAN(
	MAPB VARCHAR(255),
	TENPB VARCHAR(255),
	DIACHIPB INT NOT NULL,
	CONSTRAINT PK_PHONGBAN PRIMARY KEY (MAPB)
)
GO

CREATE TABLE DM_BANGCAP(
	LOAIBANG VARCHAR(255),
	NGAYCAPBANG DATE,
	MANV VARCHAR(255),
	MATRINHDO VARCHAR(255),
	MANGANH VARCHAR(255)
)
GO

CREATE TABLE DM_TRINHDO(
	MATRINHDO VARCHAR(255),
	TENTRINHDO VARCHAR(255),
	CONSTRAINT PK_TRINHDO PRIMARY KEY (MATRINHDO)
)
GO

CREATE TABLE DM_NGANH(
	MANGANH VARCHAR(255),
	TENNGANH VARCHAR(255),
	CONSTRAINT PK_NGANH PRIMARY KEY (MANGANH)
)
GO

CREATE TABLE DM_THUONG(
	TIENTHUONG INT NOT NULL,
	MUCDOTHUONG INT NOT NULL,
	MANV VARCHAR (255),
)
GO

CREATE TABLE DM_QHGIADINH(
	STT INT NOT NULL,
	TENNGUOIQH VARCHAR(255),
	DIACHI VARCHAR(255),
	NGAYSINH DATE,
	MANV VARCHAR(255),
)
GO

CREATE TABLE DM_KINANG(
	MAKINANG VARCHAR (255), 
	TENKINANG VARCHAR (255),
	MOTA VARCHAR (255),
	CONSTRAINT PK_KINANG PRIMARY KEY (MAKINANG)
)
GO

CREATE TABLE DM_KINANG_NV(
	MUCDO INT NOT NULL,
	MANV VARCHAR(255),
	MAKINANG VARCHAR(255),
)
GO

CREATE TABLE NV_FULLTIME(
	MANV VARCHAR(255), 
	LUONGNAM INT,
)
GO

CREATE TABLE NV_PARTTIME(
	MANV VARCHAR(255),
	LUONGGIO INT,
)
GO

CREATE TABLE NV_TUVAN(
	MANV VARCHAR(255),
	LUONGTHEOCAPBAC INT,
)
GO

--ADD FOREIGN KEY
--DM_NHANVIEN
ALTER TABLE DM_NHANVIEN ADD CONSTRAINT FK_PHONGBAN FOREIGN KEY (MAPB) REFERENCES DM_PHONGBAN(MAPB)
   
--DM_BANGCAP
ALTER TABLE DM_BANGCAP ADD CONSTRAINT FR_NHANVIEN FOREIGN KEY (MANV) REFERENCES DM_NHANVIEN(MANV)
ALTER TABLE DM_BANGCAP ADD CONSTRAINT FR_TRINHDO FOREIGN KEY (MATRINHDO) REFERENCES DM_TRINHDO(MATRINHDO)
ALTER TABLE DM_BANGCAP ADD CONSTRAINT FR_NGANH FOREIGN KEY (MANGANH) REFERENCES DM_NGANH(MANGANH)

--DM_THUONG
ALTER TABLE DM_THUONG ADD CONSTRAINT FR_NHANVIEN_THUONG FOREIGN KEY (MANV) REFERENCES DM_NHANVIEN(MANV)

--DM_QHGIADINH
ALTER TABLE DM_QHGIADINH ADD CONSTRAINT FR_NHANVIEN_GD FOREIGN KEY (MANV) REFERENCES DM_NHANVIEN(MANV)

--NV FULLTIME, PARTTIME,NV_TUVAN
ALTER TABLE NV_FULLTIME ADD CONSTRAINT FR_NHANVIEN_FULL FOREIGN KEY (MANV) REFERENCES DM_NHANVIEN(MANV)
ALTER TABLE NV_PARTTIME ADD CONSTRAINT FR_NHANVIEN_PART FOREIGN KEY (MANV) REFERENCES DM_NHANVIEN(MANV)
ALTER TABLE NV_TUVAN ADD CONSTRAINT FR_NHANVIEN_TV FOREIGN KEY (MANV) REFERENCES DM_NHANVIEN(MANV)
 
--DM_KINANG_NV
ALTER TABLE DM_KINANG_NV ADD CONSTRAINT FR_KINANG FOREIGN KEY (MAKINANG) REFERENCES DM_KINANG(MAKINANG)
ALTER TABLE DM_KINANG_NV ADD CONSTRAINT FR_NHANVIEN_KN FOREIGN KEY (MANV) REFERENCES DM_NHANVIEN(MANV)

--ADD CHECK_ DIA CHI PHONG BAN VA LUONGTHEOCAPDO
ALTER TABLE DM_PHONGBAN
ADD CONSTRAINT CHK_DIACHIPB CHECK (DIACHI >= 1 AND DIACHI <=5);

ALTER TABLE DM_THUONG
ADD CONSTRAINT CHK_MUCDOTHUONG CHECK (MUCDOTHUONG >= 1 AND MUCDOTHUONG <=5);

ALTER TABLE DM_KINANG_NV
ADD CONSTRAINT CHK_MUCDO CHECK (MUCDO >= 1 AND MUCDO <=5);
